CREATE TABLE compte(
   id_compte BIGINT GENERATED BY DEFAULT AS IDENTITY,
   pseudo VARCHAR(25)  NOT NULL,
   email VARCHAR(50)  NOT NULL,
   empreinte_mdp VARCHAR(68)  NOT NULL,
   role_admin BOOLEAN NOT NULL DEFAULT FALSE,
   PRIMARY KEY(id_compte),
   UNIQUE(pseudo),
   UNIQUE(email)
);

CREATE TABLE type_plat(
   id_type_plat BIGINT GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(25)  NOT NULL CHECK (nom<> ''),
   rang SMALLINT NOT NULL,
   PRIMARY KEY(id_type_plat),
   UNIQUE(nom)
);

CREATE TABLE plat(
   id_plat BIGINT GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(50)  NOT NULL CHECK (nom <>''),
   nb_personnes SMALLINT NOT NULL CHECK( nb_personnes > 0),
   cout NUMERIC(9,2) CHECK ( cout >= 0 ),
   id_type_plat BIGINT NOT NULL,
   PRIMARY KEY(id_plat),
   UNIQUE(nom),
   FOREIGN KEY(id_type_plat) REFERENCES type_plat(id_type_plat)
);

CREATE TABLE unite(
   id_unite BIGINT GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(10)  NOT NULL CHECK(nom <> ''),
   abrev VARCHAR(3)  NOT NULL CHECK(abrev <> ''),
   PRIMARY KEY(id_unite),
   UNIQUE(nom),
   UNIQUE(abrev)
);
