-------
-- Ajout d'extension à PostgreSQL
-------
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-------
-- compte
-------

INSERT INTO compte (id_compte, pseudo, empreinte_mdp, email, role_admin ) VALUES
( 1, 'admin', crypt( 'admin', gen_salt('bf')), 'admin@mail.com', TRUE ),
( 2, 'chef', crypt( 'chef', gen_salt('bf')), 'chef@mail.com', FALSE ),
( 3, 'job', crypt( 'job', gen_salt('bf')), 'job@mail.com', FALSE ),
( 4, 'max', crypt('max', gen_salt('bf')), 'max@mail.com', FALSE ),
( 5, 'mika', crypt('mika', gen_salt('bf')), 'mika@mail.com', FALSE ),
( 6, 'tom', crypt('tom', gen_salt('bf')), 'tom@mail.com', FALSE ),
( 7, 'eva', crypt('eva', gen_salt('bf')), 'eva@mail.com', FALSE ),
( 8, 'lulu', crypt('lulu', gen_salt('bf')), 'lulu@mail.com', FALSE ),
( 9, 'nina', crypt('nina', gen_salt('bf')), 'nina@mail.com', FALSE ),
(10, 'kim', crypt('kim', gen_salt('bf')), 'kim@mail.com', FALSE ),
(11, 'jules', crypt('jules', gen_salt('bf')), 'jules@mail.com', FALSE),
(12, 'raph', crypt('raph', gen_salt('bf')), 'raph@mail.com', FALSE),
(13, 'chris', crypt('chris', gen_salt('bf')), 'chris@mail.com', FALSE),
(14, 'dan', crypt('dan', gen_salt('bf')), 'dan@mail.com', FALSE),
(15, 'dany', crypt('dany', gen_salt('bf')), 'dany@mail.com', FALSE),
(16, 'steph', crypt('steph', gen_salt('bf')), 'steph@mail.com', FALSE),
(17, 'fran', crypt('fran', gen_salt('bf')), 'fran@mail.com', FALSE),
(18, 'fred', crypt('fred', gen_salt('bf')), 'fred@mail.com', FALSE),
(19, 'luc', crypt('luc', gen_salt('bf')), 'luc@mail.com', FALSE),
(20, 'paul', crypt('paul', gen_salt('bf')), 'paul@mail.com', FALSE),
(21, 'gwen', crypt('gwen', gen_salt('bf')), 'gwen@mail.com', FALSE),
(22, 'emi', crypt('emi', gen_salt('bf')), 'emi@mail.com', FALSE),
(23, 'tim', crypt('tim', gen_salt('bf')), 'tim@mail.com', FALSE),
(24, 'math', crypt('math', gen_salt('bf')), 'math@mail.com', FALSE),
(25, 'vic', crypt('vic', gen_salt('bf')), 'vic@mail.com', FALSE),
(26, 'vince', crypt('vince', gen_salt('bf')), 'vince@mail.com', FALSE),
(27, 'rick', crypt('rick', gen_salt('bf')), 'rick@mail.com', FALSE),
(28, 'kiki', crypt('kiki', gen_salt('bf')), 'kiki@mail.com', FALSE),
(29, 'coco', crypt('coco', gen_salt('bf')), 'coco@mail.com', FALSE),
(30, 'mimi', crypt('mimi', gen_salt('bf')), 'mimi@mail.com', FALSE),
(31, 'lili', crypt('lili', gen_salt('bf')), 'lili@mail.com', FALSE),
(32, 'gigi', crypt('gigi', gen_salt('bf')), 'gigi@mail.com', FALSE),
(33, 'titi', crypt('titi', gen_salt('bf')), 'titi@mail.com', FALSE),
(34, 'fifi', crypt('fifi', gen_salt('bf')), 'fifi@mail.com', FALSE),
(35, 'mick', crypt('mick', gen_salt('bf')), 'mick@mail.com', FALSE),
(36, 'juju', crypt('juju', gen_salt('bf')), 'juju@mail.com', FALSE),
(37, 'toto', crypt('toto', gen_salt('bf')), 'toto@mail.com', FALSE),
(38, 'nino', crypt('nino', gen_salt('bf')), 'nino@mail.com', FALSE),
(39, 'bibi', crypt('bibi', gen_salt('bf')), 'bibi@mail.com', FALSE),
(40, 'fafa', crypt('fafa', gen_salt('bf')), 'fafa@mail.com', FALSE),
(41, 'philou', crypt('philou', gen_salt('bf')), 'philou@mail.com', FALSE),
(42, 'tony', crypt('tony', gen_salt('bf')), 'tony@mail.com', FALSE),
(43, 'bernie', crypt('bernie', gen_salt('bf')), 'bernie@mail.com', FALSE),
(44, 'cathy', crypt('cathy', gen_salt('bf')), 'cathy@mail.com', FALSE),
(45, 'chacha', crypt('chacha', gen_salt('bf')), 'chacha@mail.com', FALSE),
(46, 'clem', crypt('clem', gen_salt('bf')), 'clem@mail.com', FALSE),
(47, 'dam', crypt('dam', gen_salt('bf')), 'dam@mail.com', FALSE),
(48, 'eddy', crypt('eddy', gen_salt('bf')), 'eddy@mail.com', FALSE),
(49, 'gaby', crypt('gaby', gen_salt('bf')), 'gaby@mail.com', FALSE),
(50, 'gui', crypt('gui', gen_salt('bf')), 'gui@mail.com', FALSE),
(51, 'lena', crypt('lena', gen_salt('bf')), 'lena@mail.com', FALSE),
(52, 'isa', crypt('isa', gen_salt('bf')), 'isa@mail.com', FALSE),
(53, 'jeje', crypt('jeje', gen_salt('bf')), 'jeje@mail.com', FALSE),
(54, 'nathy', crypt('nathy', gen_salt('bf')), 'nathy@mail.com', FALSE),
(55, 'oli', crypt('oli', gen_salt('bf')), 'oli@mail.com', FALSE),
(56, 'pat', crypt('pat', gen_salt('bf')), 'pat@mail.com', FALSE),
(57, 'remy', crypt('remy', gen_salt('bf')), 'remy@mail.com', FALSE),
(58, 'seb', crypt('seb', gen_salt('bf')), 'seb@mail.com', FALSE),
(59, 'xavi', crypt('xavi', gen_salt('bf')), 'xavi@mail.com', FALSE),
(60, 'yoyo', crypt('yoyo', gen_salt('bf')), 'yoyo@mail.com', FALSE),
(61, 'yves', crypt('yves', gen_salt('bf')), 'yves@mail.com', FALSE),
(62, 'auri', crypt('auri', gen_salt('bf')), 'auri@mail.com', FALSE),
(63, 'sevy', crypt('sevy', gen_salt('bf')), 'sevy@mail.com', FALSE),
(64, 'valou', crypt('valou', gen_salt('bf')), 'valou@mail.com', FALSE),
(65, 'quino', crypt('quino', gen_salt('bf')), 'quino@mail.com', FALSE),
(66, 'meli', crypt('meli', gen_salt('bf')), 'meli@mail.com', FALSE),
(67, 'caro', crypt('caro', gen_salt('bf')), 'caro@mail.com', FALSE),
(68, 'domi', crypt('domi', gen_salt('bf')), 'domi@mail.com', FALSE),
(69, 'fabi', crypt('fabi', gen_salt('bf')), 'fabi@mail.com', FALSE),
(70, 'flo', crypt('flo', gen_salt('bf')), 'flo@mail.com', FALSE),
(71, 'gege', crypt('gege', gen_salt('bf')), 'gege@mail.com', FALSE),
(72, 'hugi', crypt('hugi', gen_salt('bf')), 'hugi@mail.com', FALSE),
(73, 'jem', crypt('jem', gen_salt('bf')), 'jem@mail.com', FALSE),
(74, 'jus', crypt('jus', gen_salt('bf')), 'jus@mail.com', FALSE),
(75, 'kev', crypt('kev', gen_salt('bf')), 'kev@mail.com', FALSE),
(76, 'laury', crypt('laury', gen_salt('bf')), 'laury@mail.com', FALSE),
(77, 'ludo', crypt('ludo', gen_salt('bf')), 'ludo@mail.com', FALSE),
(78, 'mano', crypt('mano', gen_salt('bf')), 'mano@mail.com', FALSE),
(79, 'mari', crypt('mari', gen_salt('bf')), 'mari@mail.com', FALSE),
(80, 'mel', crypt('mel', gen_salt('bf')), 'mel@mail.com', FALSE),
(81, 'morg', crypt('morg', gen_salt('bf')), 'morg@mail.com', FALSE),
(82, 'nade', crypt('nade', gen_salt('bf')), 'nade@mail.com', FALSE),
(83, 'paco', crypt('paco', gen_salt('bf')), 'paco@mail.com', FALSE),
(84, 'pato', crypt('pato', gen_salt('bf')), 'pato@mail.com', FALSE),
(85, 'rom', crypt('rom', gen_salt('bf')), 'rom@mail.com', FALSE),
(86, 'sandy', crypt('sandy', gen_salt('bf')), 'sandy@mail.com', FALSE),
(87, 'solly', crypt('solly', gen_salt('bf')), 'solly@mail.com', FALSE),
(88, 'suzy', crypt('suzy', gen_salt('bf')), 'suzy@mail.com', FALSE),
(89, 'vero', crypt('vero', gen_salt('bf')), 'vero@mail.com', FALSE),
(90, 'willy', crypt('willy', gen_salt('bf')), 'willy@mail.com', FALSE),
(91, 'yassy', crypt('yassy', gen_salt('bf')), 'yassy@mail.com', FALSE),
(92, 'zoe', crypt('zoe', gen_salt('bf')), 'zoe@mail.com', FALSE),
(93, 'aime', crypt('aime', gen_salt('bf')), 'aime@mail.com', FALSE),
(94, 'ellie', crypt('ellie', gen_salt('bf')), 'ellie@mail.com', FALSE),
(95, 'izzy', crypt('izzy', gen_salt('bf')), 'izzy@mail.com', FALSE),
(96, 'berna', crypt('berna', gen_salt('bf')), 'berna@mail.com', FALSE),
(97, 'arny', crypt('arny', gen_salt('bf')), 'arny@mail.com', FALSE),
(98, 'vivi', crypt('vivi', gen_salt('bf')), 'vivi@mail.com', FALSE),
(99, 'gus', crypt('gus', gen_salt('bf')), 'gus@mail.com', FALSE),
(100, 'sisi', crypt('sisi', gen_salt('bf')), 'sisi@mail.com', FALSE),
(101, 'lolo', crypt('lolo', gen_salt('bf')), 'lolo@mail.com', FALSE),
(102, 'bob', crypt('bob', gen_salt('bf')), 'bob@mail.com', FALSE),
(103, 'nico', crypt('nico', gen_salt('bf')), 'nico@mail.com', FALSE),
(104, 'leo', crypt('leo', gen_salt('bf')), 'leo@mail.com', FALSE),
(105, 'ben', crypt('ben', gen_salt('bf')), 'ben@mail.com', FALSE),
(106, 'sam', crypt('sam', gen_salt('bf')), 'sam@mail.com', FALSE);

ALTER TABLE compte      ALTER COLUMN id_compte     RESTART WITH 107;
